name: Package Size Report

on:
  pull_request:
    branches: [dev]

jobs:
  pkg-size-report:
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          npm ci

      - name: Package size report for ucp-desktop
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          display-size: gzip
          build-command: npm run build:platforms -- --env platform=ucp-desktop
          hide-files: '*.{map,txt}'
          unchanged-files: hide

      - name: Package size report for ucp-mobile
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          display-size: gzip
          build-command: npm run build:platforms -- --env platform=ucp-mobile
          hide-files: '*.{map,txt}'
          unchanged-files: hide

      - name: Package size report for f2
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          display-size: gzip
          build-command: npm run build:platforms -- --env platform=f2
          hide-files: '*.{map,txt}'
          unchanged-files: hide

      - name: Package size report for ucp-no-ads
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          display-size: gzip
          build-command: npm run build:platforms -- --env platform=ucp-no-ads
          hide-files: '*.{map,txt}'
          unchanged-files: hide
