name: Package Size Report

on:
  pull_request:
    branches: [dev]

jobs:
  pkg-size-report:
    name: Package Size Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Package size report for platforms
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          display-size: gzip
          build-command: npm run build:platforms -- --env platform=ucp-desktop
          hide-files: '*.{map,scss,ts,txt}'
          unchanged-files: hide
