name: PR Labeler
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    if: ${{ github.actor != 'dependabot[bot]' && (!contains( github.event.pull_request.labels.*.name, 'Major change')) && (!contains( github.event.pull_request.labels.*.name, 'Minor change')) && (!contains( github.event.pull_request.labels.*.name, 'Patch change')) }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5.0.0
        with:
          configuration-path: .github/labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
