name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          nvm install
          npm ci
          npm run test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./spec/build/clover.xml
          verbose: true
